"""usermodel

Revision ID: 75c9cc4a58b
Revises: None
Create Date: 2013-06-28 09:46:46.581571

"""

# revision identifiers, used by Alembic.
revision = '75c9cc4a58b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Unicode(length=255), nullable=False),
    sa.Column('givenname', sa.Unicode(length=255), nullable=True),
    sa.Column('surname', sa.Unicode(length=255), nullable=True),
    sa.Column('last_logged', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    ### end Alembic commands ###
